/* BizFinPro — Word (.docx) export via JSZip (OOXML) */
(function (global) {
  'use strict';
  const esc = (s) => String(s == null ? '' : s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

  function exportDocx(p, F, opts) {
    opts = opts || {};
    const t = I18N.t;
    const cur = p.currency;
    const RM = (v) => FMT.money(v, cur, { decimals: 0 });
    const N = F.N;
    const bodies = [];
    const H1 = (s) => bodies.push('<w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t xml:space="preserve">' + esc(s) + '</w:t></w:r></w:p>');
    const H2 = (s) => bodies.push('<w:p><w:pPr><w:pStyle w:val="Heading2"/></w:pPr><w:r><w:t xml:space="preserve">' + esc(s) + '</w:t></w:r></w:p>');
    const P = (s, bold) => bodies.push('<w:p><w:pPr><w:pStyle w:val="' + (bold ? 'Strong' : 'Body') + '"/></w:pPr><w:r><w:t xml:space="preserve">' + esc(s) + '</w:t></w:r></w:p>');
    function table(headers, rows, moneyCols) {
      const borders = '<w:tblBorders>' + ['top', 'left', 'bottom', 'right', 'insideH', 'insideV'].map((e) => '<w:' + e + ' w:val="single" w:sz="4" w:color="D5DCE4"/>').join('') + '</w:tblBorders>';
      let xml = '<w:tbl><w:tblPr><w:tblW w:w="0" w:type="auto"/>' + borders + '</w:tblPr><w:tblGrid>';
      headers.forEach(() => { xml += '<w:gridCol w:w="' + Math.floor(9000 / headers.length) + '"/>'; });
      xml += '</w:tblGrid>';
      const cell = (txt, opts2) => {
        opts2 = opts2 || {};
        return '<w:tc><w:tcPr><w:shd w:val="clear" w:fill="' + (opts2.fill || 'FFFFFF') + '"/></w:tcPr><w:p><w:pPr><w:jc w:val="' + (opts2.right ? 'right' : 'left') + '"/></w:pPr><w:r><w:rPr><w:b w:val="' + (opts2.bold ? '1' : '0') + '"/></w:rPr><w:t xml:space="preserve">' + esc(txt) + '</w:t></w:r></w:p></w:tc>';
      };
      xml += '<w:tr>' + headers.map((h) => cell(h, { bold: true, fill: 'EEF3F8' })).join('') + '</w:tr>';
      rows.forEach((r) => { xml += '<w:tr>' + r.map((c, i) => cell(c, { right: moneyCols && i > 0 ? true : false, bold: r.__bold && i === 0 })).join('') + '</w:tr>'; });
      xml += '</w:tbl><w:p/>';
      bodies.push(xml);
    }
    const moneyRow = (label, arr) => [label].concat(Array.from({ length: N }, (_, i) => RM(arr[i + 1])));
    const yearHeads = ['']; for (let e = 1; e <= N; e++) yearHeads.push('Y' + e);

    /* Cover + TOC field */
    bodies.push('<w:p><w:pPr><w:pStyle w:val="Title"/></w:pPr><w:r><w:t>BizFinPro</w:t></w:r></w:p>');
    P(t('app.tagline'));
    P('');
    P(p.name || '', true);
    P(bizName(p));
    P(t('common.mode') + ': ' + p.financialMode + '  ·  ' + N + ' ' + t('year') + '  ·  ' + p.currency);
    P(t('reports.title') + ': ' + FMT.fmtDate(new Date().toISOString()) + '  ·  BizFinPro V1');
    bodies.push('<w:p><w:r><w:br w:type="page"/></w:r></w:p>');

    H1(t('reports.title'));
    P('Generated by BizFinPro V1 — ' + FMT.fmtDate(new Date().toISOString()));

    H1(t('reports.exec_summary'));
    table([t('reports.exec_summary'), ''], [
      [t('dashboard.total_investment'), RM(F.invest.totalInvestment)],
      [t('dashboard.revenue') + ' (Y1)', RM(F.revenue.annual[1])],
      [t('dashboard.net_profit') + ' (Y' + N + ')', RM(F.pl.netProfit[N])],
      [t('dashboard.roi'), FMT.pct(F.invest.roiTotal, 1)],
      [t('dashboard.npv'), RM(F.invest.npv)],
      [t('dashboard.irr'), F.invest.irr == null ? t('not_calculable') : FMT.pct(F.invest.irr * 100, 2)],
      [t('dashboard.payback'), F.invest.payback.paybackYear == null ? t('not_recovered') : F.invest.payback.paybackPeriod.toFixed(2) + ' ' + t('year')]
    ], false);

    H1(t('reports.profile'));
    table([t('reports.profile'), ''], [
      [t('profile.business_name'), bizName(p)], [t('profile.reg_no'), p.business.regNo || '—'],
      [t('profile.industry'), p.business.industry || '—'], [t('profile.owner'), p.business.owner || '—']
    ], false);

    H1(t('reports.assumptions'));
    const aRows = []; Model.ASSUMPTION_DEFS.forEach((d) => { const a = p.assumptions[d.key]; aRows.push([t('assumptions.' + d.key), FMT.num(a.active, d.decimals) + ' ' + d.unit]); });
    table([t('reports.assumptions'), ''], aRows, false);

    H1(t('investment.title'));
    table([t('investment.title'), ''], [
      [t('investment.capex'), RM(F.initial.capex)], [t('investment.startup'), RM(F.initial.startup)],
      [t('investment.working_capital'), RM(F.initial.workingCapital)], [t('investment.total_funding'), RM(F.initial.total)]
    ], false);

    H1(t('reports.capex'));
    table([t('capex.asset_name'), t('capex.total_cost')], p.capex.items.filter((it) => Number(it.totalCost) > 0).map((it) => [it.name, RM(it.totalCost)]), true);

    H1(t('reports.pl'));
    const plRows = [moneyRow(t('pl.revenue'), F.pl.revenue), moneyRow('COGS', F.pl.cogs), moneyRow(t('pl.gross_profit'), F.pl.grossProfit),
      moneyRow(t('pl.opex'), F.pl.opex), moneyRow(t('pl.ebitda'), F.pl.ebitda), moneyRow(t('pl.depreciation'), F.pl.dep),
      moneyRow(t('pl.ebit'), F.pl.ebit), moneyRow(t('pl.financing_cost'), F.pl.financingCost), moneyRow(t('pl.pbt'), F.pl.pbt),
      moneyRow(t('pl.tax'), F.pl.tax), moneyRow(t('pl.net_profit'), F.pl.netProfit)];
    plRows[plRows.length - 1].__bold = true;
    table(yearHeads, plRows, true);

    H1(t('reports.cashflow'));
    const cfRows = [moneyRow(t('cashflow.operating'), F.cf.operating), moneyRow(t('cashflow.investing'), F.cf.investing), moneyRow(t('cashflow.financing'), F.cf.financing),
      moneyRow(t('cashflow.net'), F.cf.net), moneyRow(t('cashflow.opening'), F.cf.opening), moneyRow(t('cashflow.closing'), F.cf.closing)];
    cfRows[cfRows.length - 1].__bold = true;
    table(yearHeads, cfRows, true);

    H1(t('nav.analysis'));
    table([t('analysis.title') || t('nav.analysis'), ''], [
      [t('analysis.be_units'), F.invest.breakeven.beUnits == null ? t('not_calculable') : String(Math.round(F.invest.breakeven.beUnits))],
      [t('dashboard.roi'), FMT.pct(F.invest.roiTotal, 1)],
      [t('dashboard.npv'), RM(F.invest.npv)],
      [t('dashboard.irr'), F.invest.irr == null ? t('not_calculable') : FMT.pct(F.invest.irr * 100, 2)],
      [t('dashboard.payback'), F.invest.payback.paybackYear == null ? t('not_recovered') : F.invest.payback.paybackPeriod.toFixed(2) + ' ' + t('year')]
    ], false);

    H1(t('reports.financing'));
    if (p.financialMode === 'KONVENSIONAL') {
      const fr = F.financing.conventional.loans.map((l, i) => {
        const sch = F.financing.conventional.schedules[i];
        return [l.name || t('financing.' + l.structure), RM(l.amount), FMT.pct(l.rate, 2), RM(sch ? sch.totalInterest : 0)];
      });
      table([t('financing.title'), t('financing.loan_amount'), t('financing.interest_rate'), t('financing.interest')], fr, true);
    } else {
      const d = F.financing.islamic.detail || {};
      table([t('reports.islamic'), ''], [
        [t('financing.structure'), t('financing.structures.' + F.financing.islamic.structure)],
        [t('dashboard.total_investment'), RM(F.financing.injected0)],
        [t('murabahah.profit_paid'), RM(d.profitTotal || 0)]
      ], false);
    }

    if (p.financialMode === 'SYARIAH') {
      H1(t('reports.screening'));
      const sc = p.shariah.screening || {};
      table([t('screening.title'), ''], [
        [t('screening.business_activity'), sc.activity || '—'], [t('screening.riba'), sc.riba || '—'],
        [t('screening.gharar'), sc.gharar || '—'], [t('screening.maysir'), sc.maysir || '—']
      ], false);
      H1(t('reports.review'));
      const rv = p.shariah.review || {};
      table([t('review.title'), ''], [
        [t('review.adviser'), rv.adviser || '—'], [t('review.review_date'), rv.date || '—'],
        [t('review.status'), rv.status ? t('review.' + rv.status) : '—'], [t('review.notes'), rv.notes || '—']
      ], false);
      H1(t('reports.disclaimer'));
      P(t('screening.disclaimer'));
    }

    /* Build document.xml */
    const bodyXml = '<w:body>' + bodies.join('') +
      '<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1134" w:right="1134" w:bottom="1134" w:left="1134" w:header="708" w:footer="708" w:gutter="0"/></w:sectPr></w:body>';
    const documentXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>' +
      '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' + bodyXml + '</w:document>';
    const stylesXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">' +
      '<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:rPr><w:sz w:val="22"/></w:rPr></w:style>' +
      '<w:style w:type="paragraph" w:styleId="Body"><w:name w:val="Body"/></w:style>' +
      '<w:style w:type="paragraph" w:styleId="Strong"><w:name w:val="Strong"/><w:rPr><w:b/></w:rPr></w:style>' +
      '<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:rPr><w:sz w:val="56"/><w:b/><w:color w:val="0B1220"/></w:rPr></w:style>' +
      '<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="Heading1"/><w:rPr><w:sz w:val="30"/><w:b/><w:color w:val="0369A1"/></w:rPr></w:style>' +
      '<w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="Heading2"/><w:rPr><w:sz w:val="26"/><w:b/><w:color w:val="0EA5E9"/></w:rPr></w:style>' +
      '</w:styles>';
    const contentTypes = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">' +
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>' +
      '<Default Extension="xml" ContentType="application/xml"/>' +
      '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>' +
      '<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>' +
      '</Types>';
    const rels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>' +
      '</Relationships>';
    const docRels = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">' +
      '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>' +
      '</Relationships>';

    const entries = [
      { name: '[Content_Types].xml', data: contentTypes },
      { name: '_rels/.rels', data: rels },
      { name: 'word/document.xml', data: documentXml },
      { name: 'word/styles.xml', data: stylesXml },
      { name: 'word/_rels/document.xml.rels', docRels }
    ];
    const zipBytes = zipStore(entries);
    const filename = ExportXlsx.fileBase(p, 'docx') + '.docx';
    if (!FMT.saveFile(zipBytes, filename, 'application/vnd.openxmlformats-officedocument.wordprocessingml.document')) {
      const blob = new Blob([zipBytes], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = filename;
      document.body.appendChild(a); a.click();
      setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 2500);
    }
  }

  /* Minimal STORE-mode ZIP writer (no compression, deflate-free, deterministic) */
  const CRC_TABLE = (() => {
    const t = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
      t[n] = c >>> 0;
    }
    return t;
  })();
  function crc32(bytes) {
    let c = 0xFFFFFFFF;
    for (let i = 0; i < bytes.length; i++) c = CRC_TABLE[(c ^ bytes[i]) & 0xFF] ^ (c >>> 8);
    return (c ^ 0xFFFFFFFF) >>> 0;
  }
  function u16(v) { return [v & 0xFF, (v >> 8) & 0xFF]; }
  function u32(v) { return [v & 0xFF, (v >> 8) & 0xFF, (v >> 16) & 0xFF, (v >> 24) & 0xFF]; }
  function zipStore(entries) {
    const enc = new TextEncoder();
    const parts = [];
    const central = [];
    let offset = 0;
    entries.forEach((e) => {
      const nameB = enc.encode(e.name);
      const dataB = enc.encode(e.data);
      const crc = crc32(dataB);
      const local = [].concat(
        u32(0x04034b50), u16(20), u16(0x0800), u16(0), u16(0), u16(0),
        u32(crc), u32(dataB.length), u32(dataB.length),
        u16(nameB.length), u16(0)
      );
      parts.push(new Uint8Array(local), nameB, dataB);
      const cent = [].concat(
        u32(0x02014b50), u16(20), u16(20), u16(0x0800), u16(0), u16(0), u16(0),
        u32(crc), u32(dataB.length), u32(dataB.length),
        u16(nameB.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset)
      );
      central.push(new Uint8Array(cent), nameB);
      offset += local.length + nameB.length + dataB.length;
    });
    let centralSize = 0;
    central.forEach((c) => { centralSize += c.length; });
    const end = [].concat(
      u32(0x06054b50), u16(0), u16(0), u16(entries.length), u16(entries.length),
      u32(centralSize), u32(offset), u16(0)
    );
    const all = new Uint8Array(offset + centralSize + end.length);
    let pos = 0;
    parts.forEach((p) => { all.set(p, pos); pos += p.length; });
    central.forEach((c) => { all.set(c, pos); pos += c.length; });
    all.set(new Uint8Array(end), pos);
    return all;
  }

  function bizName(p) { return (p.business && p.business.businessName) || p.name || 'Project'; }
  global.ExportDocx = { exportDocx, bizName };
})(typeof window !== 'undefined' ? window : globalThis);
